#!/usr/bin/env zsh

# Basic ZSHRC
autoload -Uz compinit
compinit

# ZINIT
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load Theme
[[ -f ~/.zsh_theme ]] && source ~/.zsh_theme

# Plugin Initialization
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting

# Preferred editor for local and remote sessions
export EDITOR='vim'

[[ -f ~/.nick ]] && source ~/.nick
[[ -f ~/.homebrewrc ]] && source ~/.homebrewrc

# Add "go" to PATH
export PATH="$PATH:/usr/local/go/bin"

# Add NVM to PATH
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Completions
[[ -f ~/.k8s_completion ]] && source ~/.k8s_completion
[[ -f ~/.docker_completion ]] && source ~/.docker_completion
[[ -f "$NVM_DIR/zsh_completion" ]] && source "$NVM_DIR/zsh_completion"

# Datadog-specific
[[ -f ~/.datadog ]] && source ~/.datadog

true

