#!/usr/bin/env zsh
alias chez="chezmoi"

alias ls="ls --color=auto"
alias grep="grep --color=auto"

alias n="nvim"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias push="git push"
alias pull="git pull"

alias d="docker"
alias k="kubectl"
alias kctx="kubectx"
alias mk="minikube"
