#!/usr/bin/env zsh

# Chezmoi
alias chez="chezmoi"
alias chezpush="chezmoi git add . && chezmoi git commit && chezmoi git push"
alias chezpull="chezmoi update --apply"

# Bash
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Neovim
alias n="nvim"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

# Tmux
alias t="tmux"
alias tls="tmux ls"
alias ta="tmux attach -t"

# Git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias push="git push"
alias pull="git pull"

# Docker + Kubernetes
alias d="docker"
alias k="kubectl"
alias kctx="kubectx"
alias mk="minikube"

