[window]
startup_mode = "Maximized"

[font]
size = 32

[keyboard]
bindings = [
	{ key = "Backspace", mods = "Super", chars = "\u0015" },
	{ key = "ArrowLeft", mods = "Option", chars = "\u001b\u0062" },
	{ key = "ArrowRight", mods = "Option", chars = "\u001b\u0066" },
]
